### PR TITLE
Make crop sizes customizable through Wordpress filters

### PR DESCRIPTION
**Pull request by devbydave**
Could I please suggest something along these lines, so that theme developers are able to customise which sizes appear in the cropping interface, and how they are labelled for the user?

Currrently these don't appear to be customisable, so this small tweak would be a big help.

### CODE REVIEW

**Comment by JiveDig** [comment]
Just came here looking for the same thing. This would be really useful so clients don't get overwhelmed. Sometimes I only want to allow them to crop 2-3 sizes, not all the others that are registered.

Was going to suggest a filter on https://github.com/sirulli/yoimages-crop/blob/e827700a5bfd64d8615832f5a2cc7ba3d9d1117d/inc/utils.php#L37 but @devbydave's solution looks like it may work as well.

**Comment by fagia** [comment]
Thanks @devbydave and @JiveDig for the code contribution and the suggestion.
We're planning to allow the choice of labels and formats enabled right from the plugin settings interface.
We'll keep you updated, regards
   Team Sirulli

**Comment by JiveDig** [comment]
Great news. YoImages crop has been really great for us and our clients.

**Comment by fagia** [comment]
hi @devbydave and @JiveDig! we've just pushed to master branch the capability to manage via crop settings page the labels for each crop format and to enable/disable crop formats individually.
If you want to give this a try directly from sources and give feedback before we publish this version to WP it would be helpful!
Regards,
   Team Sirulli

**Comment by JiveDig** [comment]
Excellent! Will try to test tomorrow. We've been using the plugin on every client site for almost a year now. So grateful to have it!

**Pull request closed without merging**
