### PR TITLE
Feature : Crop all image sizes with same ratio at once

### PR DESCRIPTION
**Pull request by leopoiroux**
Big refactoring + added feature "Crop all image sizes with same ratio at once"
Resolve Issue #47

### CODE REVIEW

**Comment by fagia** [comment]
thanks for submitting PR, we'll review it within the next month

**Comment by leopoiroux** [comment]
Hello, is it possible to accept my PR or to position myself as a project maintainer? Our Agency is currently working on an OpenSource WordPress distribution that must include your plugin. If the PR is not accepted, we will be forced to fork the project to make it installable by composer under our name. We'd prefer to keep your version.

**Comment by fagia** [comment]
Hello @leopoiroux 
as you have noticed, it has been a while since the last active developments and fixes to the plugin.
If you're interested, we can take the discussion offline regarding the maintenance handover, in case feel free to reach us via hello@sirulli.org
Regarding the specific PR, at a first glance, there a couple of issue that prevents it from being merged as is:

- dependency in composer.json targeting "raccourci/yoimages-commons" => why it is not "https://github.com/sirulli/yoimages-commons"?
- lot changes related to formatting that make harder to grasp the actual changes => try to keep in the PR only the changes that actually relates to cropping all image sizes with same ratio at once (and, in case, issue another pull request for formatting-related changes)

Best regards

**Comment by leopoiroux** [comment]
This PR is closed and transferred to a specific branch 👍 
https://github.com/sirulli/yoimages-crop/pull/9

**Pull request closed without merging**
